using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.HttpResults;
using static System.Net.Mime.MediaTypeNames;
using System.Text.Json.Serialization;

namespace TrabalhoBancoDeDados.api.Entities
{
    public class Bloco
    {

      //  CREATE TABLE "Blocos" (
      //    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
      //    "Name" text NOT NULL,
      //    "UniversidadeId" integer NOT NULL,
      //    CONSTRAINT "PK_Blocos" PRIMARY KEY("Id"),
      //    CONSTRAINT "FK_Blocos_Universidades_UniversidadeId" FOREIGN KEY("UniversidadeId") REFERENCES "Universidades" ("Id") ON DELETE CASCADE
      //);

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; } = string.Empty;

   
        [ForeignKey("UniversidadeId")]
        [JsonIgnore]
        public Universidade? Universidade { get; set; }

        [Required]
        public int UniversidadeId { get; set; }

        public ICollection<Sala> Salas { get; set; } = new List<Sala>();
    }
}
