using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http.HttpResults;
using System.Text.Json.Serialization;

namespace TrabalhoBancoDeDados.api.Entities
{
    public class Sala
    {
      //  CREATE TABLE "Salas" (
      //    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
      //    "Number" integer NOT NULL,
      //    "BlocoId" integer NOT NULL,
      //    CONSTRAINT "PK_Salas" PRIMARY KEY("Id"),
      //    CONSTRAINT "FK_Salas_Blocos_BlocoId" FOREIGN KEY("BlocoId") REFERENCES "Blocos" ("Id") ON DELETE CASCADE
      //);

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required]
        public int Number { get; set; }

        
        [ForeignKey("BlocoId")]
        [JsonIgnore]
        public Bloco? Bloco { get; set; }
        [Required]
        public int BlocoId { get; set; }
    }
}
