using Microsoft.AspNetCore.Http.HttpResults;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using static System.Net.Mime.MediaTypeNames;

namespace TrabalhoBancoDeDados.api.Entities
{
    public class Universidade
    {

      //  CREATE TABLE "Universidades" (
      //    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
      //    "Nome" text NOT NULL,
      //    CONSTRAINT "PK_Universidades" PRIMARY KEY("Id")
      //);

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; } = string.Empty;

        public ICollection<Bloco> Blocos { get; set; } = new List<Bloco>();
    }
}
