// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrabalhoBancoDeDados.api.DbContexts;

#nullable disable

namespace TrabalhoBancoDeDados.api.Migrations
{
    [DbContext(typeof(UnivaliContext))]
    partial class UnivaliContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UniversidadeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadeId");

                    b.ToTable("Blocos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A",
                            UniversidadeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "B",
                            UniversidadeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "C",
                            UniversidadeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "1",
                            UniversidadeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "2",
                            UniversidadeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "3",
                            UniversidadeId = 2
                        });
                });

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlocoId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BlocoId = 1,
                            Number = 101
                        },
                        new
                        {
                            Id = 2,
                            BlocoId = 1,
                            Number = 102
                        },
                        new
                        {
                            Id = 3,
                            BlocoId = 2,
                            Number = 201
                        },
                        new
                        {
                            Id = 4,
                            BlocoId = 2,
                            Number = 202
                        },
                        new
                        {
                            Id = 5,
                            BlocoId = 3,
                            Number = 301
                        },
                        new
                        {
                            Id = 6,
                            BlocoId = 3,
                            Number = 302
                        },
                        new
                        {
                            Id = 7,
                            BlocoId = 4,
                            Number = 401
                        },
                        new
                        {
                            Id = 8,
                            BlocoId = 4,
                            Number = 402
                        },
                        new
                        {
                            Id = 9,
                            BlocoId = 5,
                            Number = 501
                        },
                        new
                        {
                            Id = 10,
                            BlocoId = 5,
                            Number = 502
                        },
                        new
                        {
                            Id = 11,
                            BlocoId = 6,
                            Number = 601
                        },
                        new
                        {
                            Id = 12,
                            BlocoId = 6,
                            Number = 602
                        });
                });

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Universidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Universidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Univali"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Uniavan"
                        });
                });

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Bloco", b =>
                {
                    b.HasOne("TrabalhoBancoDeDados.api.Entities.Universidade", "Universidade")
                        .WithMany("Blocos")
                        .HasForeignKey("UniversidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Universidade");
                });

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Sala", b =>
                {
                    b.HasOne("TrabalhoBancoDeDados.api.Entities.Bloco", "Bloco")
                        .WithMany("Salas")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bloco");
                });

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Bloco", b =>
                {
                    b.Navigation("Salas");
                });

            modelBuilder.Entity("TrabalhoBancoDeDados.api.Entities.Universidade", b =>
                {
                    b.Navigation("Blocos");
                });
#pragma warning restore 612, 618
        }
    }
}
